environments:
  all:
    pipelines:
      - dotnet-build
      - dotnet-package
pipelines:
  dotnet-build:
    group: Gauge-Dotnet
    materials:
      dotnet:
        git: https://github.com/getgauge/gauge-dotnet.git
    stages:
      - build:
          jobs:
            unit-test:
              resources:
               - windows
              tasks:
               - exec:
                   command: run
                   arguments:
                    - test
  dotnet-package:
    group: Gauge-Dotnet
    materials:
      dotnet:
        git: https://github.com/getgauge/gauge-dotnet.git
      upstream:
        pipeline: dotnet-build
        stage: build
    stages:
      - artifact:
          jobs:
            installer:
              resources:
               - windows
              tasks:
               - exec:
                   command: run
                   arguments:
                    - package
              artifacts:
               - build:
                   source: deploy/
