os:
  - osx
  - linux
env:
  - GAUGE_TELEMETRY_ENABLED=false GAUGE_PREFIX=/tmp TERM=dumb
before_install:
  - mozroots --import --sync
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export JAVA_HOME="/usr/lib/jvm/java-8-oracle"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install Caskroom/cask/java; fi
addons:
  apt:
    packages:
      - oracle-java8-set-default
install:
  - curl -sSfL https://raw.githubusercontent.com/getgauge/infrastructure/master/nightly_scripts/install_latest_gauge_nightly.sh | bash
  - export PATH=/tmp/bin:$PATH
  - gauge version
  - gauge config gauge_repository_url  https://raw.githubusercontent.com/getgauge/gauge-nightly-repository/master/

language: csharp

dotnet: 2.1.3
script:
  - ./run.sh build
  - ./run.sh test
  - ./run.sh forceinstall
  - git clone https://github.com/getgauge/gauge-tests.git
  - cd gauge-tests
  - gauge install
  - gauge -v
  - ./gradlew clean dotnetFT